openapi: 3.0.0
tags:
  - name: products
    description: produkty
info:
  description: Testovací api pro seznámení s novým nástrojem
  contact:
    email: vojtech.buba@peckadesign.cz
  title: Test api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                Základní produkt:
                  value:
                    id: 1
                    name: Apple iPhone 8 64 GB
                    price: 399
                    description: Super telefon
                Drahý iphone:
                  value:
                    id: 2
                    name: Apple iPhone XS 256 GB
                    price: 999
                    description: Drahý ipohne
      operationId: get-products-id
      description: Získáni informací o produktu
components:
  schemas:
    Product:
      title: Product
      type: object
      description: Entita produktu
      x-examples:
        Basic product:
          id: 10
          name: Apple iPhone 8 64 GB
          price: 399
          description: Skvělý mobil
      properties:
        id:
          type: number
        name:
          type: string
        price:
          type: number
        description:
          type: string
